- name: Ensure k3s config directory exists
  file:
    path: /etc/rancher/k3s
    state: directory
    mode: "0755"

- name: Configure k3s (disable Traefik)
  copy:
    dest: /etc/rancher/k3s/config.yaml
    content: |
      disable:
        - traefik
  register: k3s_config

- name: Install k3s
  shell: |
    curl -sfL https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s

- name: Restart k3s if config changed
  systemd:
    name: k3s
    state: restarted
  when: k3s_config.changed
